//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PreAdamantParser.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace PreAdamant.Compiler.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPreAdamantParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class PreAdamantParserBaseListener : IPreAdamantParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] PreAdamantParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] PreAdamantParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.usingDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingDirective([NotNull] PreAdamantParser.UsingDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.usingDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingDirective([NotNull] PreAdamantParser.UsingDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] PreAdamantParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] PreAdamantParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.namespaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceName([NotNull] PreAdamantParser.NamespaceNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.namespaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceName([NotNull] PreAdamantParser.NamespaceNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NamespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDeclaration([NotNull] PreAdamantParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NamespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDeclaration([NotNull] PreAdamantParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ClassDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] PreAdamantParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ClassDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] PreAdamantParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.VariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] PreAdamantParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.VariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] PreAdamantParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.FunctionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] PreAdamantParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.FunctionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] PreAdamantParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ExternalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalDeclaration([NotNull] PreAdamantParser.ExternalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ExternalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalDeclaration([NotNull] PreAdamantParser.ExternalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Precondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrecondition([NotNull] PreAdamantParser.PreconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Precondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrecondition([NotNull] PreAdamantParser.PreconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Postcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostcondition([NotNull] PreAdamantParser.PostconditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Postcondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostcondition([NotNull] PreAdamantParser.PostconditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] PreAdamantParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] PreAdamantParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.baseTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseTypes([NotNull] PreAdamantParser.BaseTypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.baseTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseTypes([NotNull] PreAdamantParser.BaseTypesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessModifier([NotNull] PreAdamantParser.AccessModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessModifier([NotNull] PreAdamantParser.AccessModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.safetyModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSafetyModifier([NotNull] PreAdamantParser.SafetyModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.safetyModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSafetyModifier([NotNull] PreAdamantParser.SafetyModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.classInheritanceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassInheritanceModifier([NotNull] PreAdamantParser.ClassInheritanceModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.classInheritanceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassInheritanceModifier([NotNull] PreAdamantParser.ClassInheritanceModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.methodInheritanceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodInheritanceModifier([NotNull] PreAdamantParser.MethodInheritanceModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.methodInheritanceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodInheritanceModifier([NotNull] PreAdamantParser.MethodInheritanceModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.conversionModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConversionModifier([NotNull] PreAdamantParser.ConversionModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.conversionModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConversionModifier([NotNull] PreAdamantParser.ConversionModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.asyncModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsyncModifier([NotNull] PreAdamantParser.AsyncModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.asyncModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsyncModifier([NotNull] PreAdamantParser.AsyncModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameters([NotNull] PreAdamantParser.TypeParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameters([NotNull] PreAdamantParser.TypeParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameter([NotNull] PreAdamantParser.TypeParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameter([NotNull] PreAdamantParser.TypeParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArguments([NotNull] PreAdamantParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArguments([NotNull] PreAdamantParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.identifierOrPredefinedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierOrPredefinedType([NotNull] PreAdamantParser.IdentifierOrPredefinedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.identifierOrPredefinedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierOrPredefinedType([NotNull] PreAdamantParser.IdentifierOrPredefinedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.IdentifierName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierName([NotNull] PreAdamantParser.IdentifierNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.IdentifierName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierName([NotNull] PreAdamantParser.IdentifierNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.GenericName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericName([NotNull] PreAdamantParser.GenericNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.GenericName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericName([NotNull] PreAdamantParser.GenericNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.UnqualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnqualifiedName([NotNull] PreAdamantParser.UnqualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.UnqualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnqualifiedName([NotNull] PreAdamantParser.UnqualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.QualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] PreAdamantParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.QualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] PreAdamantParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NamedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedType([NotNull] PreAdamantParser.NamedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NamedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedType([NotNull] PreAdamantParser.NamedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.FunctionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionType([NotNull] PreAdamantParser.FunctionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.FunctionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionType([NotNull] PreAdamantParser.FunctionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.TupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleType([NotNull] PreAdamantParser.TupleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.TupleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleType([NotNull] PreAdamantParser.TupleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.MaybeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaybeType([NotNull] PreAdamantParser.MaybeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.MaybeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaybeType([NotNull] PreAdamantParser.MaybeTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.PointerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointerType([NotNull] PreAdamantParser.PointerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.PointerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointerType([NotNull] PreAdamantParser.PointerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ImmutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImmutableReferenceType([NotNull] PreAdamantParser.ImmutableReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ImmutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImmutableReferenceType([NotNull] PreAdamantParser.ImmutableReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.MutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMutableReferenceType([NotNull] PreAdamantParser.MutableReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.MutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMutableReferenceType([NotNull] PreAdamantParser.MutableReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.OwnedImmutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwnedImmutableReferenceType([NotNull] PreAdamantParser.OwnedImmutableReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.OwnedImmutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwnedImmutableReferenceType([NotNull] PreAdamantParser.OwnedImmutableReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.OwnedMutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwnedMutableReferenceType([NotNull] PreAdamantParser.OwnedMutableReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.OwnedMutableReferenceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwnedMutableReferenceType([NotNull] PreAdamantParser.OwnedMutableReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnType([NotNull] PreAdamantParser.ReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnType([NotNull] PreAdamantParser.ReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.lifetime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLifetime([NotNull] PreAdamantParser.LifetimeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.lifetime"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLifetime([NotNull] PreAdamantParser.LifetimeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.funcTypeParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncTypeParameterList([NotNull] PreAdamantParser.FuncTypeParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.funcTypeParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncTypeParameterList([NotNull] PreAdamantParser.FuncTypeParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.funcTypeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncTypeParameter([NotNull] PreAdamantParser.FuncTypeParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.funcTypeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncTypeParameter([NotNull] PreAdamantParser.FuncTypeParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.constExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstExpression([NotNull] PreAdamantParser.ConstExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.constExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstExpression([NotNull] PreAdamantParser.ConstExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.typeParameterConstraintClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameterConstraintClause([NotNull] PreAdamantParser.TypeParameterConstraintClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.typeParameterConstraintClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameterConstraintClause([NotNull] PreAdamantParser.TypeParameterConstraintClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ConstructorConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorConstraint([NotNull] PreAdamantParser.ConstructorConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ConstructorConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorConstraint([NotNull] PreAdamantParser.ConstructorConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.TypeConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeConstraint([NotNull] PreAdamantParser.TypeConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.TypeConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeConstraint([NotNull] PreAdamantParser.TypeConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.TypeListParameterConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeListParameterConstraint([NotNull] PreAdamantParser.TypeListParameterConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.TypeListParameterConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeListParameterConstraint([NotNull] PreAdamantParser.TypeListParameterConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Constructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructor([NotNull] PreAdamantParser.ConstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Constructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructor([NotNull] PreAdamantParser.ConstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Destructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDestructor([NotNull] PreAdamantParser.DestructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Destructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDestructor([NotNull] PreAdamantParser.DestructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ConversionMethod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConversionMethod([NotNull] PreAdamantParser.ConversionMethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ConversionMethod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConversionMethod([NotNull] PreAdamantParser.ConversionMethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] PreAdamantParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] PreAdamantParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Accessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessor([NotNull] PreAdamantParser.AccessorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Accessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessor([NotNull] PreAdamantParser.AccessorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Indexer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexer([NotNull] PreAdamantParser.IndexerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Indexer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexer([NotNull] PreAdamantParser.IndexerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.Method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod([NotNull] PreAdamantParser.MethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.Method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod([NotNull] PreAdamantParser.MethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.OperatorOverload"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOverload([NotNull] PreAdamantParser.OperatorOverloadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.OperatorOverload"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOverload([NotNull] PreAdamantParser.OperatorOverloadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NestedClassDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedClassDeclaration([NotNull] PreAdamantParser.NestedClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NestedClassDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedClassDeclaration([NotNull] PreAdamantParser.NestedClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] PreAdamantParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] PreAdamantParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.namedParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedParameter([NotNull] PreAdamantParser.NamedParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.namedParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedParameter([NotNull] PreAdamantParser.NamedParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.selfParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelfParameter([NotNull] PreAdamantParser.SelfParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.selfParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelfParameter([NotNull] PreAdamantParser.SelfParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.parameterModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterModifier([NotNull] PreAdamantParser.ParameterModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.parameterModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterModifier([NotNull] PreAdamantParser.ParameterModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.constructorInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorInitializer([NotNull] PreAdamantParser.ConstructorInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.constructorInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorInitializer([NotNull] PreAdamantParser.ConstructorInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] PreAdamantParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] PreAdamantParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.BlockMethodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockMethodBody([NotNull] PreAdamantParser.BlockMethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.BlockMethodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockMethodBody([NotNull] PreAdamantParser.BlockMethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NoMethodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoMethodBody([NotNull] PreAdamantParser.NoMethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NoMethodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoMethodBody([NotNull] PreAdamantParser.NoMethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.overloadableOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOverloadableOperator([NotNull] PreAdamantParser.OverloadableOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.overloadableOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOverloadableOperator([NotNull] PreAdamantParser.OverloadableOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.VariableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationStatement([NotNull] PreAdamantParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.VariableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationStatement([NotNull] PreAdamantParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.UnsafeBlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsafeBlockStatement([NotNull] PreAdamantParser.UnsafeBlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.UnsafeBlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsafeBlockStatement([NotNull] PreAdamantParser.UnsafeBlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.BlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatement([NotNull] PreAdamantParser.BlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.BlockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatement([NotNull] PreAdamantParser.BlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.EmptyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement([NotNull] PreAdamantParser.EmptyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.EmptyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement([NotNull] PreAdamantParser.EmptyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ExpressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] PreAdamantParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ExpressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] PreAdamantParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ReturnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] PreAdamantParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ReturnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] PreAdamantParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ThrowStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrowStatement([NotNull] PreAdamantParser.ThrowStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ThrowStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrowStatement([NotNull] PreAdamantParser.ThrowStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.IfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] PreAdamantParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.IfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] PreAdamantParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.LetIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetIfStatement([NotNull] PreAdamantParser.LetIfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.LetIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetIfStatement([NotNull] PreAdamantParser.LetIfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ForStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] PreAdamantParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ForStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] PreAdamantParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.WhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] PreAdamantParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.WhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] PreAdamantParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.DeleteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteStatement([NotNull] PreAdamantParser.DeleteStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.DeleteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteStatement([NotNull] PreAdamantParser.DeleteStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ContinueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] PreAdamantParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ContinueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] PreAdamantParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclaration([NotNull] PreAdamantParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclaration([NotNull] PreAdamantParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NullCheckExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullCheckExpression([NotNull] PreAdamantParser.NullCheckExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NullCheckExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullCheckExpression([NotNull] PreAdamantParser.NullCheckExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.StringLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteralExpression([NotNull] PreAdamantParser.StringLiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.StringLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteralExpression([NotNull] PreAdamantParser.StringLiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.XorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXorExpression([NotNull] PreAdamantParser.XorExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.XorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXorExpression([NotNull] PreAdamantParser.XorExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NameExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameExpression([NotNull] PreAdamantParser.NameExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NameExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameExpression([NotNull] PreAdamantParser.NameExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.InExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInExpression([NotNull] PreAdamantParser.InExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.InExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInExpression([NotNull] PreAdamantParser.InExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.UnaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] PreAdamantParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.UnaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] PreAdamantParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.OrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpression([NotNull] PreAdamantParser.OrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.OrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpression([NotNull] PreAdamantParser.OrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.IntLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntLiteralExpression([NotNull] PreAdamantParser.IntLiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.IntLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntLiteralExpression([NotNull] PreAdamantParser.IntLiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NewObjectExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewObjectExpression([NotNull] PreAdamantParser.NewObjectExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NewObjectExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewObjectExpression([NotNull] PreAdamantParser.NewObjectExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.AndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpression([NotNull] PreAdamantParser.AndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.AndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpression([NotNull] PreAdamantParser.AndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.AssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] PreAdamantParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.AssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] PreAdamantParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.SelfExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelfExpression([NotNull] PreAdamantParser.SelfExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.SelfExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelfExpression([NotNull] PreAdamantParser.SelfExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.BooleanLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteralExpression([NotNull] PreAdamantParser.BooleanLiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.BooleanLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteralExpression([NotNull] PreAdamantParser.BooleanLiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.EqualityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] PreAdamantParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.EqualityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] PreAdamantParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.MultiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] PreAdamantParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.MultiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] PreAdamantParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.CallExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallExpression([NotNull] PreAdamantParser.CallExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.CallExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallExpression([NotNull] PreAdamantParser.CallExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NullLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullLiteralExpression([NotNull] PreAdamantParser.NullLiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NullLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullLiteralExpression([NotNull] PreAdamantParser.NullLiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ParenthesizedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesizedExpression([NotNull] PreAdamantParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ParenthesizedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesizedExpression([NotNull] PreAdamantParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.AdditiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] PreAdamantParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.AdditiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] PreAdamantParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.IfExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfExpression([NotNull] PreAdamantParser.IfExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.IfExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfExpression([NotNull] PreAdamantParser.IfExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.NewExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewExpression([NotNull] PreAdamantParser.NewExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.NewExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewExpression([NotNull] PreAdamantParser.NewExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.UninitializedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUninitializedExpression([NotNull] PreAdamantParser.UninitializedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.UninitializedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUninitializedExpression([NotNull] PreAdamantParser.UninitializedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.TryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTryExpression([NotNull] PreAdamantParser.TryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.TryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTryExpression([NotNull] PreAdamantParser.TryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.MagnitudeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMagnitudeExpression([NotNull] PreAdamantParser.MagnitudeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.MagnitudeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMagnitudeExpression([NotNull] PreAdamantParser.MagnitudeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.MemberExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberExpression([NotNull] PreAdamantParser.MemberExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.MemberExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberExpression([NotNull] PreAdamantParser.MemberExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ComparativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparativeExpression([NotNull] PreAdamantParser.ComparativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ComparativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparativeExpression([NotNull] PreAdamantParser.ComparativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.CastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpression([NotNull] PreAdamantParser.CastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.CastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpression([NotNull] PreAdamantParser.CastExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.CharLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharLiteralExpression([NotNull] PreAdamantParser.CharLiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.CharLiteralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharLiteralExpression([NotNull] PreAdamantParser.CharLiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.DotDotExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotDotExpression([NotNull] PreAdamantParser.DotDotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.DotDotExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotDotExpression([NotNull] PreAdamantParser.DotDotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.LambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpression([NotNull] PreAdamantParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.LambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpression([NotNull] PreAdamantParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.CoalesceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCoalesceExpression([NotNull] PreAdamantParser.CoalesceExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.CoalesceExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCoalesceExpression([NotNull] PreAdamantParser.CoalesceExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PreAdamantParser.ArrayAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccessExpression([NotNull] PreAdamantParser.ArrayAccessExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PreAdamantParser.ArrayAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccessExpression([NotNull] PreAdamantParser.ArrayAccessExpressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace PreAdamant.Compiler.Parser
